*Replace this text with your own name and a brief description of what this notebook does.*

## Homework 13-2

Are more long green taxi trips taken between midnight and noon than between noon and midnight?

Use you green taxi dataset from Lab 4 (and later labs).  Compute the median trip distance for taxi trips started in the am (between midnight and noon), and the median trip distance for taxi trips started in the pm (between noon and midnight).

Use the `lpep_pickup_datatime` column as the starting time for the trip (so specify it is a date/time column when you read in the CSV file).

In [2]:
import matplotlib.pyplot as plt
import pandas as pd

taxi = pd.read_csv("../../data/Sept1_2021_Green_Taxi_Trip_Data.csv",parse_dates = ["lpep_pickup_datetime"])
taxi.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2021-09-01 00:00:11,09/01/2021 12:01:39 AM,N,1.0,74,74,1.0,0.02,3.0,0.5,0.5,0.00,0.0,NaN,0.3,4.30,2.0,1.0,0.00
1,2,2021-09-01 00:00:26,09/01/2021 12:09:38 AM,N,1.0,95,56,1.0,1.41,8.0,0.5,0.5,1.00,0.0,NaN,0.3,10.30,1.0,1.0,0.00
2,2,2021-09-01 00:01:27,09/01/2021 12:23:14 AM,N,1.0,93,256,1.0,11.07,31.5,0.5,0.5,6.56,0.0,NaN,0.3,39.36,1.0,1.0,0.00
3,1,2021-09-01 00:01:31,09/01/2021 12:15:14 AM,N,1.0,255,36,1.0,2.80,11.5,1.0,0.5,3.95,0.0,NaN,0.3,17.25,1.0,1.0,0.00
4,2,2021-09-01 00:02:08,09/01/2021 12:24:51 AM,N,5.0,93,144,4.0,10.64,65.0,0.0,0.0,0.00,0.0,NaN,0.3,68.05,2.0,2.0,2.75

In [3]:
# create a dataframe of trips started between midnight and 11:59am
am_filter = taxi["lpep_pickup_datetime"].dt.hour < 12
am_trips = taxi[am_filter]
am_trips.tail()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
1229,2,2021-09-01 11:57:00,09/01/2021 12:13:00 PM,NaN,NaN,35,258,NaN,4.14,32.67,2.75,0.0,0.0,0.00,NaN,0.3,35.72,NaN,NaN,NaN
1230,2,2021-09-01 11:57:09,09/01/2021 12:17:26 PM,N,1.0,75,152,1.0,3.42,15.00,0.00,0.5,0.0,0.00,NaN,0.3,15.80,1.0,1.0,0.0
1231,2,2021-09-01 11:58:02,09/01/2021 12:01:22 PM,N,1.0,41,42,1.0,0.80,5.00,0.00,0.5,0.0,0.00,NaN,0.3,5.80,2.0,1.0,0.0
1232,2,2021-09-01 11:59:00,09/01/2021 12:38:00 PM,NaN,NaN,228,234,NaN,0.00,20.07,5.50,0.0,0.0,10.17,NaN,0.3,36.04,NaN,NaN,NaN
1233,2,2021-09-01 11:59:14,09/01/2021 12:09:00 PM,N,1.0,95,135,1.0,1.92,9.00,0.00,0.5,0.0,0.00,NaN,0.3,9.80,2.0,1.0,0.0

In [4]:
# create a dataframe of trips started between noon and 11:59pm.
pm_filter = taxi["lpep_pickup_datetime"].dt.hour >= 12
pm_trips = taxi[pm_filter]
pm_trips.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
1234,2,2021-09-01 12:00:00,09/01/2021 12:26:00 PM,NaN,NaN,154,227,NaN,11.46,27.25,2.75,0.0,0.00,0.00,NaN,0.3,30.30,NaN,NaN,NaN
1235,2,2021-09-01 12:00:09,09/01/2021 12:11:45 PM,N,1.0,7,7,1.0,1.50,9.00,0.00,0.5,0.00,0.00,NaN,0.3,9.80,2.0,1.0,0.0
1236,1,2021-09-01 12:00:22,09/01/2021 12:22:20 PM,N,1.0,41,239,1.0,0.00,13.20,0.00,0.5,0.00,0.00,NaN,0.3,14.00,1.0,1.0,0.0
1237,2,2021-09-01 12:01:00,09/01/2021 12:48:00 PM,NaN,NaN,91,262,NaN,17.50,58.41,0.00,0.0,14.38,6.55,NaN,0.3,82.39,NaN,NaN,NaN
1238,2,2021-09-01 12:01:02,09/01/2021 12:01:27 PM,N,1.0,223,223,1.0,0.04,-2.50,0.00,-0.5,0.00,0.00,NaN,-0.3,-3.30,3.0,1.0,0.0

In [5]:
# compute the median am trip distance
am_trips["trip_distance"].median()

3.09

In [6]:
# compute the median pm trip distance
pm_trips["trip_distance"].median()

2.57

1. Which median is larger?  Do you think the difference is significant or the result of chance?

Write your answers below.

1. The median trip distance for am trips is longer than the median trip distance for pm trips.  The difference is 0.52 miles, which seems like it might be significant given the size of the data set.